import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import Nav from "@/components/Nav";
import { ChevronDown } from "lucide-react";

const FAQItem = ({ question, answer }: { question: string; answer: React.ReactNode }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-[#222]">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full py-6 flex justify-between items-center text-left hover:text-drift-green transition-colors focus:outline-none"
      >
        <span className="font-display text-xl md:text-2xl text-white">{question}</span>
        <ChevronDown className={`w-5 h-5 text-[#666] transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`} />
      </button>
      <div 
        className={`overflow-hidden transition-all duration-300 ease-in-out ${isOpen ? "max-h-96 opacity-100 pb-8" : "max-h-0 opacity-0"}`}
      >
        <p className="text-[#999] leading-relaxed font-light text-lg">
          {answer}
        </p>
      </div>
    </div>
  );
};

const HelpCenter = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#060606] text-[#e0e0e0] font-body selection:bg-white selection:text-black">
      <Nav />
      
      <main className="pt-24 md:pt-32 pb-16 md:pb-24 px-5 md:px-8 max-w-5xl mx-auto relative z-10">
        
        {/* Navigation Back */}
        <div className="mb-12">
          <button 
            onClick={() => navigate("/")}
            className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#666] hover:text-white transition-colors"
          >
            [ ← Return to Index ]
          </button>
        </div>

        {/* Hero */}
        <header className="mb-16 md:mb-24">
          <p className="font-mono text-[10px] uppercase tracking-widest text-drift-green mb-6">Support & FAQ</p>
          <h1 className="font-display text-4xl sm:text-5xl md:text-7xl tracking-tighter leading-[1] text-white mb-8">
            How Can We Help?
          </h1>
          <p className="text-xl md:text-2xl leading-relaxed font-light text-[#d0d0d0] max-w-3xl">
            Everything you need to know about using RatioX, securing your data, and optimizing your mutual fund portfolio.
          </p>
        </header>

        {/* FAQ Section */}
        <div className="mb-24">
          <h2 className="font-mono text-[10px] uppercase tracking-widest text-[#666] mb-8 border-b border-[#222] pb-4">Frequently Asked Questions</h2>
          
          <div className="flex flex-col">
            <FAQItem 
              question="How does RatioX calculate hidden fees?" 
              answer="RatioX looks at the Total Expense Ratio (TER) of the 'Regular' mutual funds in your portfolio, and compares them against the TER of their exact 'Direct' counterparts. The difference between these two ratios is the hidden commission paid to your broker. We project this difference over 10-20 years with compound interest to show you the real amount of wealth you are losing."
            />
            <FAQItem 
              question="Do I need to pay for RatioX?" 
              answer={<>No, RatioX is completely free to use. We do not charge subscriptions, nor do we run ads on the platform. However, running the platform costs money. If we helped you save money, you can choose to support us by visiting the <a href="/manifesto" className="text-white underline decoration-[#444] hover:decoration-white">Manifesto page</a>.</>}
            />
            <FAQItem 
              question="Is it safe to upload my CAS (Consolidated Account Statement)?" 
              answer="Yes. We strictly use read-only access to parse the text within your PDF statement locally and securely. We do not store your raw statements, and we have zero access to make any transactions or withdrawals. Your data is encrypted and remains under your control."
            />
            <FAQItem 
              question="Why did my CAS upload fail?" 
              answer="Usually, this happens if the password entered was incorrect, or if the PDF was generated by a non-standard provider (we currently best support CAMS/KFintech statements). Ensure you enter the correct PAN-based password when prompted."
            />
            <FAQItem 
              question="Are you SEBI Registered Advisors?" 
              answer="No. RatioX is a mathematical analysis and educational tool built to expose hidden fees. We do not provide personalized financial or investment advice. You should always consult with a SEBI-registered fee-only planner before making major financial decisions."
            />
          </div>
        </div>

        {/* Contact Block */}
        <div className="border border-[#222] bg-[#0a0a0a] p-8 md:p-12 relative overflow-hidden group">
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff02_1px,transparent_1px),linear-gradient(to_bottom,#ffffff02_1px,transparent_1px)] bg-[size:1rem_1rem]"></div>
          
          <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
            <div>
              <h3 className="font-display text-3xl md:text-4xl text-white mb-4">Still need help?</h3>
              <p className="text-[#999] leading-relaxed font-light text-lg max-w-xl">
                We are actively working on setting up dedicated support channels and a community forum. For now, if you experience major bugs, please check back as we deploy updates regularly.
              </p>
            </div>
            
            <div className="font-mono text-[10px] text-[#555] uppercase tracking-widest border-l-2 border-[#333] pl-4 space-y-2">
              <p>System Status: <span className="text-drift-green">Operational</span></p>
              <p>Support Channels: <span className="text-amber">Coming Soon</span></p>
            </div>
          </div>
        </div>
        
        <div className="mt-16 md:mt-24 pt-6 border-t border-[#222]">
          <p className="text-[9px] font-mono text-[#444] leading-relaxed uppercase tracking-[0.1em]">
            Disclaimer: RatioX is a mathematical analysis tool for educational purposes. We are not SEBI-registered financial advisors. We do not provide investment advice.
          </p>
        </div>
      </main>
    </div>
  );
};

export default HelpCenter;
